/**
 * Supabase database schema type for Bhairavi Bhajans.
 *
 * Mirrors the shape generated by `supabase gen types` (Database -> schema ->
 * Tables/Views/Functions). Keeping it hand-written and in sync with
 * `supabase/schema.sql`. Update this file whenever you change the schema.
 */
export interface Database {
  public: {
    Tables: {
      programs: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          program_type: string | null;
          date: string;
          start_time: string | null;
          end_time: string | null;
          location: string | null;
          status: string;
          image: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          program_type?: string | null;
          date: string;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          status?: string;
          image?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          program_type?: string | null;
          date?: string;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          status?: string;
          image?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      availability: {
        Row: {
          id: string;
          date: string;
          status: string;
          note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          date: string;
          status: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          date?: string;
          status?: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      enquiries: {
        Row: {
          id: string;
          name: string;
          phone: string;
          email: string | null;
          event_type: string | null;
          event_date: string | null;
          event_location: string | null;
          message: string | null;
          source: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          email?: string | null;
          event_type?: string | null;
          event_date?: string | null;
          event_location?: string | null;
          message?: string | null;
          source?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string;
          email?: string | null;
          event_type?: string | null;
          event_date?: string | null;
          event_location?: string | null;
          message?: string | null;
          source?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      whatsapp_clicks: {
        Row: {
          id: string;
          page: string | null;
          program_id: string | null;
          visitor_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          page?: string | null;
          program_id?: string | null;
          visitor_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          page?: string | null;
          program_id?: string | null;
          visitor_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      visitor_events: {
        Row: {
          id: string;
          visitor_id: string | null;
          path: string;
          referrer: string | null;
          user_agent: string | null;
          device_type: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          visitor_id?: string | null;
          path: string;
          referrer?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          visitor_id?: string | null;
          path?: string;
          referrer?: string | null;
          user_agent?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      admin_users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
}